# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"
    loaders:
        default:
            filesystem:
                locator: filesystem_insecure
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                upscale:
                    min: [275, 275]
                thumbnail:
                    size: [275, 275]
                    mode: outbound
        admin_thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [60, 60]
                    mode: inset
        full_view:
            quality: 90
            filters:
                thumbnail:
                    size: [1500, 1000]
                    mode: inset
